# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import test as module_0


def test_case_0():
    bool_0 = True
    str_0 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_0 == "Equilateral triangle"


def test_case_1():
    str_0 = "Aug@uoo"
    str_1 = module_0.triangle(str_0, str_0, str_0)
    assert str_1 == "Equilateral triangle"
    int_0 = -2518
    str_2 = module_0.triangle(int_0, str_0, int_0)
    assert str_2 == "Isosceles triangle"


def test_case_2():
    bool_0 = True
    bool_1 = False
    str_0 = module_0.triangle(bool_1, bool_1, bool_0)
    assert str_0 == "Isosceles triangle"
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    none_type_0 = None
    int_0 = -1385
    int_1 = -1481
    str_1 = module_0.triangle(none_type_0, int_0, int_1)
    assert str_1 == "Scalene triangle"
    str_2 = module_0.triangle(dict_0, bool_0, bool_0)
    assert str_2 == "Isosceles triangle"


def test_case_3():
    bool_0 = False
    str_0 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_0 == "Equilateral triangle"
    str_1 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_1 == "Equilateral triangle"
    int_0 = 1441
    str_2 = module_0.triangle(int_0, str_0, str_0)
    assert str_2 == "Isosceles triangle"
    str_3 = module_0.triangle(bool_0, str_0, int_0)
    assert str_3 == "Scalene triangle"
